-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC

# USER_ID가 동일한 PRODUCT_ID 2개 이상 샀을 경우 각각 출력
# USER_ID 기준 오름차순, PRODUCT_ID 기준 내림차순 정렬